services:
  - type: web
    name: php-app
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: DATABASE_URL
        value: your_database_url

